### ISSUE TITLE
map should be source-map aware?

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/broccoli-stew#16]

**Comment by stefanpenner** [comment]
https://github.com/Rich-Harris/magic-string

The current API for stew#map is as follows

```js
var map = require('broccoli-map').map;

var dist = map('lib', function(content, relativePath) {
   return 'new content'; // for file at 'relativePath'
});
```

`content` is a regularly string, but this means soruce-map is now entirely manual. What would be more interesting is, if we handled source mapping by default. For example, if `content` was in-stead an instance of @rich-harris's [magic-string](https://github.com/Rich-Harris/magic-string) we would get reasonable source map transformations out-of-the box.

example:

```
var map = require('broccoli-map').map;

var dist = map('lib', function(content, relativePath) {
   content.prepend('/* I AM A COMMENT */');
   return content;
});
```

question:

* enforce inline source maps or ...
* what else are we missing?

**Comment by Rich-Harris** [comment]
@stefanpenner would be interested to see if magic-string can support the kinds of uses you envisage, or whether it needs some additional methods. What kinds of things is map used for?

**Comment by stefanpenner** [comment]
@Rich-Harris my idea behind `map` is 1:1 transforms.

for example:

```js
map(find('foo/**/*.js'), function(content) {
  content.prepend(licenseString);
  return content;
});
```

**Comment by stefanpenner** [comment]
> @stefanpenner would be interested to see if magic-string can support the kinds of uses you envisage

ya, some experimentation is needed.

**Comment by twokul** [comment]
@stefanpenner awesome, can you assign it to me (helps to track things I need to work on)

**Comment by stefanpenner** [comment]
i assumed magic string supported the input source maps, but i suppose i was to hasty...

@Rich-Harris am i crazy, or that isn't actually supported yet?

**Comment by Rich-Harris** [comment]
@stefanpenner I'm of the opinion that tools shouldn't attempt to account for input sourcemaps - I've often found it to be a source of bugs. In my view, it's much better (and most likely more efficient) to do it in a single step, at the end. Otherwise *everyone* has to account for input sourcemaps, with the unnecessary burden that that entails in terms of additional code, most likely an extra dependency or two, API design (which is probably going to differ from one tool to the next, confusingly), and finicky tests, for every single tool that generates a sourcemap.

I wrote [sorcery](https://github.com/rich-harris/sorcery) to solve this exact problem.
